depend on rustc-serialize 0.3.20 to fix build failures
Newer versions of rust halt compilation with:

  error[E0642]: patterns aren't allowed in methods without bodies

  rustc-serialize-0.3.19/src/serialize.rs:147:45
      |
  147 |                                             &f_name: &str,
      |                                             ^^^^^^^

Issue: https://github.com/systemd-cron/systemd-cron-next/issues/46